/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthorityAuditRouteImport } from './routes/authority/audit'
import { Route as AuthorityDashboardRouteImport } from './routes/authority/dashboard'
import { Route as AuthorityNotificationsRouteImport } from './routes/authority/notifications'
import { Route as AuthorityRolesRouteImport } from './routes/authority/roles'
import { Route as AuthoritySearchRouteImport } from './routes/authority/search'
import { Route as OperatorAgentsRouteImport } from './routes/operator/agents'
import { Route as OperatorAircraftRouteImport } from './routes/operator/aircraft'
import { Route as OperatorApplyRouteImport } from './routes/operator/apply'
import { Route as OperatorDashboardRouteImport } from './routes/operator/dashboard'
import { Route as OperatorDocumentsRouteImport } from './routes/operator/documents'
import { Route as OperatorNotificationsRouteImport } from './routes/operator/notifications'
import { Route as OperatorPaymentsRouteImport } from './routes/operator/payments'
import { Route as OperatorProfileRouteImport } from './routes/operator/profile'
import { Route as OperatorRegistrationRouteImport } from './routes/operator/registration'
import { Route as AuthorityApplicationsIndexRouteImport } from './routes/authority/applications/index'
import { Route as AuthorityApplicationsReferenceRouteImport } from './routes/authority/applications/$reference'
import { Route as AuthorityApprovalIndexRouteImport } from './routes/authority/approval/index'
import { Route as AuthorityApprovalReferenceRouteImport } from './routes/authority/approval/$reference'
import { Route as AuthorityFinanceIndexRouteImport } from './routes/authority/finance/index'
import { Route as AuthorityFinanceReferenceRouteImport } from './routes/authority/finance/$reference'
import { Route as AuthorityPermitsIndexRouteImport } from './routes/authority/permits/index'
import { Route as AuthorityPermitsPermitNumberRouteImport } from './routes/authority/permits/$permitNumber'
import { Route as AuthorityTechnicalIndexRouteImport } from './routes/authority/technical/index'
import { Route as OperatorAircraftAircraftIdRouteImport } from './routes/operator/aircraft/$aircraftId'
import { Route as OperatorApplicationsIndexRouteImport } from './routes/operator/applications/index'
import { Route as OperatorApplicationsReferenceRouteImport } from './routes/operator/applications/$reference'
import { Route as OperatorPermitsIndexRouteImport } from './routes/operator/permits/index'
import { Route as OperatorPermitsPermitNumberRouteImport } from './routes/operator/permits/$permitNumber'
import { Route as OperatorRevisionPermitNumberRouteImport } from './routes/operator/revision.$permitNumber'
import { Route as AuthorityApplicationsReferenceIndexRouteImport } from './routes/authority/applications/$reference/index'
import { Route as AuthorityApplicationsReferenceTechnicalRouteImport } from './routes/authority/applications/$reference/technical'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityAuditRoute = AuthorityAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityDashboardRoute = AuthorityDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityNotificationsRoute = AuthorityNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityRolesRoute = AuthorityRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthoritySearchRoute = AuthoritySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthorityRoute,
} as any)
const OperatorAgentsRoute = OperatorAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAircraftRoute = OperatorAircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorApplyRoute = OperatorApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorDashboardRoute = OperatorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorDocumentsRoute = OperatorDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorNotificationsRoute = OperatorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPaymentsRoute = OperatorPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorProfileRoute = OperatorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorRegistrationRoute = OperatorRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => OperatorRoute,
} as any)
const AuthorityApplicationsIndexRoute =
  AuthorityApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthorityRoute,
  } as any)
const AuthorityApplicationsReferenceRoute =
  AuthorityApplicationsReferenceRouteImport.update({
    id: '/applications/$reference',
    path: '/applications/$reference',
    getParentRoute: () => AuthorityRoute,
  } as any)
const AuthorityApprovalIndexRoute = AuthorityApprovalIndexRouteImport.update({
  id: '/approval/',
  path: '/approval/',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityApprovalReferenceRoute =
  AuthorityApprovalReferenceRouteImport.update({
    id: '/approval/$reference',
    path: '/approval/$reference',
    getParentRoute: () => AuthorityRoute,
  } as any)
const AuthorityFinanceIndexRoute = AuthorityFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityFinanceReferenceRoute =
  AuthorityFinanceReferenceRouteImport.update({
    id: '/finance/$reference',
    path: '/finance/$reference',
    getParentRoute: () => AuthorityRoute,
  } as any)
const AuthorityPermitsIndexRoute = AuthorityPermitsIndexRouteImport.update({
  id: '/permits/',
  path: '/permits/',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityPermitsPermitNumberRoute =
  AuthorityPermitsPermitNumberRouteImport.update({
    id: '/permits/$permitNumber',
    path: '/permits/$permitNumber',
    getParentRoute: () => AuthorityRoute,
  } as any)
const AuthorityTechnicalIndexRoute = AuthorityTechnicalIndexRouteImport.update({
  id: '/technical/',
  path: '/technical/',
  getParentRoute: () => AuthorityRoute,
} as any)
const OperatorAircraftAircraftIdRoute =
  OperatorAircraftAircraftIdRouteImport.update({
    id: '/$aircraftId',
    path: '/$aircraftId',
    getParentRoute: () => OperatorAircraftRoute,
  } as any)
const OperatorApplicationsIndexRoute =
  OperatorApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorApplicationsReferenceRoute =
  OperatorApplicationsReferenceRouteImport.update({
    id: '/applications/$reference',
    path: '/applications/$reference',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorPermitsIndexRoute = OperatorPermitsIndexRouteImport.update({
  id: '/permits/',
  path: '/permits/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPermitsPermitNumberRoute =
  OperatorPermitsPermitNumberRouteImport.update({
    id: '/permits/$permitNumber',
    path: '/permits/$permitNumber',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorRevisionPermitNumberRoute =
  OperatorRevisionPermitNumberRouteImport.update({
    id: '/revision/$permitNumber',
    path: '/revision/$permitNumber',
    getParentRoute: () => OperatorRoute,
  } as any)
const AuthorityApplicationsReferenceIndexRoute =
  AuthorityApplicationsReferenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorityApplicationsReferenceRoute,
  } as any)
const AuthorityApplicationsReferenceTechnicalRoute =
  AuthorityApplicationsReferenceTechnicalRouteImport.update({
    id: '/technical',
    path: '/technical',
    getParentRoute: () => AuthorityApplicationsReferenceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/verify': typeof VerifyRoute
  '/authority/audit': typeof AuthorityAuditRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/notifications': typeof AuthorityNotificationsRoute
  '/authority/roles': typeof AuthorityRolesRoute
  '/authority/search': typeof AuthoritySearchRoute
  '/operator/agents': typeof OperatorAgentsRoute
  '/operator/aircraft': typeof OperatorAircraftRouteWithChildren
  '/operator/apply': typeof OperatorApplyRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/payments': typeof OperatorPaymentsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/registration': typeof OperatorRegistrationRoute
  '/authority/applications/$reference': typeof AuthorityApplicationsReferenceRouteWithChildren
  '/authority/approval/$reference': typeof AuthorityApprovalReferenceRoute
  '/authority/finance/$reference': typeof AuthorityFinanceReferenceRoute
  '/authority/permits/$permitNumber': typeof AuthorityPermitsPermitNumberRoute
  '/operator/aircraft/$aircraftId': typeof OperatorAircraftAircraftIdRoute
  '/operator/applications/$reference': typeof OperatorApplicationsReferenceRoute
  '/operator/permits/$permitNumber': typeof OperatorPermitsPermitNumberRoute
  '/operator/revision/$permitNumber': typeof OperatorRevisionPermitNumberRoute
  '/authority/applications/': typeof AuthorityApplicationsIndexRoute
  '/authority/approval/': typeof AuthorityApprovalIndexRoute
  '/authority/finance/': typeof AuthorityFinanceIndexRoute
  '/authority/permits/': typeof AuthorityPermitsIndexRoute
  '/authority/technical/': typeof AuthorityTechnicalIndexRoute
  '/operator/applications/': typeof OperatorApplicationsIndexRoute
  '/operator/permits/': typeof OperatorPermitsIndexRoute
  '/authority/applications/$reference/technical': typeof AuthorityApplicationsReferenceTechnicalRoute
  '/authority/applications/$reference/': typeof AuthorityApplicationsReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/verify': typeof VerifyRoute
  '/authority/audit': typeof AuthorityAuditRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/notifications': typeof AuthorityNotificationsRoute
  '/authority/roles': typeof AuthorityRolesRoute
  '/authority/search': typeof AuthoritySearchRoute
  '/operator/agents': typeof OperatorAgentsRoute
  '/operator/aircraft': typeof OperatorAircraftRouteWithChildren
  '/operator/apply': typeof OperatorApplyRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/payments': typeof OperatorPaymentsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/registration': typeof OperatorRegistrationRoute
  '/authority/approval/$reference': typeof AuthorityApprovalReferenceRoute
  '/authority/finance/$reference': typeof AuthorityFinanceReferenceRoute
  '/authority/permits/$permitNumber': typeof AuthorityPermitsPermitNumberRoute
  '/operator/aircraft/$aircraftId': typeof OperatorAircraftAircraftIdRoute
  '/operator/applications/$reference': typeof OperatorApplicationsReferenceRoute
  '/operator/permits/$permitNumber': typeof OperatorPermitsPermitNumberRoute
  '/operator/revision/$permitNumber': typeof OperatorRevisionPermitNumberRoute
  '/authority/applications': typeof AuthorityApplicationsIndexRoute
  '/authority/approval': typeof AuthorityApprovalIndexRoute
  '/authority/finance': typeof AuthorityFinanceIndexRoute
  '/authority/permits': typeof AuthorityPermitsIndexRoute
  '/authority/technical': typeof AuthorityTechnicalIndexRoute
  '/operator/applications': typeof OperatorApplicationsIndexRoute
  '/operator/permits': typeof OperatorPermitsIndexRoute
  '/authority/applications/$reference/technical': typeof AuthorityApplicationsReferenceTechnicalRoute
  '/authority/applications/$reference': typeof AuthorityApplicationsReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/verify': typeof VerifyRoute
  '/authority/audit': typeof AuthorityAuditRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/notifications': typeof AuthorityNotificationsRoute
  '/authority/roles': typeof AuthorityRolesRoute
  '/authority/search': typeof AuthoritySearchRoute
  '/operator/agents': typeof OperatorAgentsRoute
  '/operator/aircraft': typeof OperatorAircraftRouteWithChildren
  '/operator/apply': typeof OperatorApplyRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/documents': typeof OperatorDocumentsRoute
  '/operator/notifications': typeof OperatorNotificationsRoute
  '/operator/payments': typeof OperatorPaymentsRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/operator/registration': typeof OperatorRegistrationRoute
  '/authority/applications/$reference': typeof AuthorityApplicationsReferenceRouteWithChildren
  '/authority/approval/$reference': typeof AuthorityApprovalReferenceRoute
  '/authority/finance/$reference': typeof AuthorityFinanceReferenceRoute
  '/authority/permits/$permitNumber': typeof AuthorityPermitsPermitNumberRoute
  '/operator/aircraft/$aircraftId': typeof OperatorAircraftAircraftIdRoute
  '/operator/applications/$reference': typeof OperatorApplicationsReferenceRoute
  '/operator/permits/$permitNumber': typeof OperatorPermitsPermitNumberRoute
  '/operator/revision/$permitNumber': typeof OperatorRevisionPermitNumberRoute
  '/authority/applications/': typeof AuthorityApplicationsIndexRoute
  '/authority/approval/': typeof AuthorityApprovalIndexRoute
  '/authority/finance/': typeof AuthorityFinanceIndexRoute
  '/authority/permits/': typeof AuthorityPermitsIndexRoute
  '/authority/technical/': typeof AuthorityTechnicalIndexRoute
  '/operator/applications/': typeof OperatorApplicationsIndexRoute
  '/operator/permits/': typeof OperatorPermitsIndexRoute
  '/authority/applications/$reference/technical': typeof AuthorityApplicationsReferenceTechnicalRoute
  '/authority/applications/$reference/': typeof AuthorityApplicationsReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority'
    | '/login'
    | '/operator'
    | '/verify'
    | '/authority/audit'
    | '/authority/dashboard'
    | '/authority/notifications'
    | '/authority/roles'
    | '/authority/search'
    | '/operator/agents'
    | '/operator/aircraft'
    | '/operator/apply'
    | '/operator/dashboard'
    | '/operator/documents'
    | '/operator/notifications'
    | '/operator/payments'
    | '/operator/profile'
    | '/operator/registration'
    | '/authority/applications/$reference'
    | '/authority/approval/$reference'
    | '/authority/finance/$reference'
    | '/authority/permits/$permitNumber'
    | '/operator/aircraft/$aircraftId'
    | '/operator/applications/$reference'
    | '/operator/permits/$permitNumber'
    | '/operator/revision/$permitNumber'
    | '/authority/applications/'
    | '/authority/approval/'
    | '/authority/finance/'
    | '/authority/permits/'
    | '/authority/technical/'
    | '/operator/applications/'
    | '/operator/permits/'
    | '/authority/applications/$reference/technical'
    | '/authority/applications/$reference/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authority'
    | '/login'
    | '/operator'
    | '/verify'
    | '/authority/audit'
    | '/authority/dashboard'
    | '/authority/notifications'
    | '/authority/roles'
    | '/authority/search'
    | '/operator/agents'
    | '/operator/aircraft'
    | '/operator/apply'
    | '/operator/dashboard'
    | '/operator/documents'
    | '/operator/notifications'
    | '/operator/payments'
    | '/operator/profile'
    | '/operator/registration'
    | '/authority/approval/$reference'
    | '/authority/finance/$reference'
    | '/authority/permits/$permitNumber'
    | '/operator/aircraft/$aircraftId'
    | '/operator/applications/$reference'
    | '/operator/permits/$permitNumber'
    | '/operator/revision/$permitNumber'
    | '/authority/applications'
    | '/authority/approval'
    | '/authority/finance'
    | '/authority/permits'
    | '/authority/technical'
    | '/operator/applications'
    | '/operator/permits'
    | '/authority/applications/$reference/technical'
    | '/authority/applications/$reference'
  id:
    | '__root__'
    | '/'
    | '/authority'
    | '/login'
    | '/operator'
    | '/verify'
    | '/authority/audit'
    | '/authority/dashboard'
    | '/authority/notifications'
    | '/authority/roles'
    | '/authority/search'
    | '/operator/agents'
    | '/operator/aircraft'
    | '/operator/apply'
    | '/operator/dashboard'
    | '/operator/documents'
    | '/operator/notifications'
    | '/operator/payments'
    | '/operator/profile'
    | '/operator/registration'
    | '/authority/applications/$reference'
    | '/authority/approval/$reference'
    | '/authority/finance/$reference'
    | '/authority/permits/$permitNumber'
    | '/operator/aircraft/$aircraftId'
    | '/operator/applications/$reference'
    | '/operator/permits/$permitNumber'
    | '/operator/revision/$permitNumber'
    | '/authority/applications/'
    | '/authority/approval/'
    | '/authority/finance/'
    | '/authority/permits/'
    | '/authority/technical/'
    | '/operator/applications/'
    | '/operator/permits/'
    | '/authority/applications/$reference/technical'
    | '/authority/applications/$reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorityRoute: typeof AuthorityRouteWithChildren
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/audit': {
      id: '/authority/audit'
      path: '/audit'
      fullPath: '/authority/audit'
      preLoaderRoute: typeof AuthorityAuditRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/dashboard': {
      id: '/authority/dashboard'
      path: '/dashboard'
      fullPath: '/authority/dashboard'
      preLoaderRoute: typeof AuthorityDashboardRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/notifications': {
      id: '/authority/notifications'
      path: '/notifications'
      fullPath: '/authority/notifications'
      preLoaderRoute: typeof AuthorityNotificationsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/roles': {
      id: '/authority/roles'
      path: '/roles'
      fullPath: '/authority/roles'
      preLoaderRoute: typeof AuthorityRolesRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/search': {
      id: '/authority/search'
      path: '/search'
      fullPath: '/authority/search'
      preLoaderRoute: typeof AuthoritySearchRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/operator/agents': {
      id: '/operator/agents'
      path: '/agents'
      fullPath: '/operator/agents'
      preLoaderRoute: typeof OperatorAgentsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/aircraft': {
      id: '/operator/aircraft'
      path: '/aircraft'
      fullPath: '/operator/aircraft'
      preLoaderRoute: typeof OperatorAircraftRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/apply': {
      id: '/operator/apply'
      path: '/apply'
      fullPath: '/operator/apply'
      preLoaderRoute: typeof OperatorApplyRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/dashboard': {
      id: '/operator/dashboard'
      path: '/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof OperatorDashboardRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/documents': {
      id: '/operator/documents'
      path: '/documents'
      fullPath: '/operator/documents'
      preLoaderRoute: typeof OperatorDocumentsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/notifications': {
      id: '/operator/notifications'
      path: '/notifications'
      fullPath: '/operator/notifications'
      preLoaderRoute: typeof OperatorNotificationsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/payments': {
      id: '/operator/payments'
      path: '/payments'
      fullPath: '/operator/payments'
      preLoaderRoute: typeof OperatorPaymentsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/profile': {
      id: '/operator/profile'
      path: '/profile'
      fullPath: '/operator/profile'
      preLoaderRoute: typeof OperatorProfileRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/registration': {
      id: '/operator/registration'
      path: '/registration'
      fullPath: '/operator/registration'
      preLoaderRoute: typeof OperatorRegistrationRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/authority/applications/': {
      id: '/authority/applications/'
      path: '/applications'
      fullPath: '/authority/applications/'
      preLoaderRoute: typeof AuthorityApplicationsIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/applications/$reference': {
      id: '/authority/applications/$reference'
      path: '/applications/$reference'
      fullPath: '/authority/applications/$reference'
      preLoaderRoute: typeof AuthorityApplicationsReferenceRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/approval/': {
      id: '/authority/approval/'
      path: '/approval'
      fullPath: '/authority/approval/'
      preLoaderRoute: typeof AuthorityApprovalIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/approval/$reference': {
      id: '/authority/approval/$reference'
      path: '/approval/$reference'
      fullPath: '/authority/approval/$reference'
      preLoaderRoute: typeof AuthorityApprovalReferenceRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/finance/': {
      id: '/authority/finance/'
      path: '/finance'
      fullPath: '/authority/finance/'
      preLoaderRoute: typeof AuthorityFinanceIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/finance/$reference': {
      id: '/authority/finance/$reference'
      path: '/finance/$reference'
      fullPath: '/authority/finance/$reference'
      preLoaderRoute: typeof AuthorityFinanceReferenceRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/permits/': {
      id: '/authority/permits/'
      path: '/permits'
      fullPath: '/authority/permits/'
      preLoaderRoute: typeof AuthorityPermitsIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/permits/$permitNumber': {
      id: '/authority/permits/$permitNumber'
      path: '/permits/$permitNumber'
      fullPath: '/authority/permits/$permitNumber'
      preLoaderRoute: typeof AuthorityPermitsPermitNumberRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/technical/': {
      id: '/authority/technical/'
      path: '/technical'
      fullPath: '/authority/technical/'
      preLoaderRoute: typeof AuthorityTechnicalIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/operator/aircraft/$aircraftId': {
      id: '/operator/aircraft/$aircraftId'
      path: '/$aircraftId'
      fullPath: '/operator/aircraft/$aircraftId'
      preLoaderRoute: typeof OperatorAircraftAircraftIdRouteImport
      parentRoute: typeof OperatorAircraftRoute
    }
    '/operator/applications/': {
      id: '/operator/applications/'
      path: '/applications'
      fullPath: '/operator/applications/'
      preLoaderRoute: typeof OperatorApplicationsIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/applications/$reference': {
      id: '/operator/applications/$reference'
      path: '/applications/$reference'
      fullPath: '/operator/applications/$reference'
      preLoaderRoute: typeof OperatorApplicationsReferenceRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/permits/': {
      id: '/operator/permits/'
      path: '/permits'
      fullPath: '/operator/permits/'
      preLoaderRoute: typeof OperatorPermitsIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/permits/$permitNumber': {
      id: '/operator/permits/$permitNumber'
      path: '/permits/$permitNumber'
      fullPath: '/operator/permits/$permitNumber'
      preLoaderRoute: typeof OperatorPermitsPermitNumberRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/revision/$permitNumber': {
      id: '/operator/revision/$permitNumber'
      path: '/revision/$permitNumber'
      fullPath: '/operator/revision/$permitNumber'
      preLoaderRoute: typeof OperatorRevisionPermitNumberRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/authority/applications/$reference/': {
      id: '/authority/applications/$reference/'
      path: '/'
      fullPath: '/authority/applications/$reference/'
      preLoaderRoute: typeof AuthorityApplicationsReferenceIndexRouteImport
      parentRoute: typeof AuthorityApplicationsReferenceRoute
    }
    '/authority/applications/$reference/technical': {
      id: '/authority/applications/$reference/technical'
      path: '/technical'
      fullPath: '/authority/applications/$reference/technical'
      preLoaderRoute: typeof AuthorityApplicationsReferenceTechnicalRouteImport
      parentRoute: typeof AuthorityApplicationsReferenceRoute
    }
  }
}

interface AuthorityApplicationsReferenceRouteChildren {
  AuthorityApplicationsReferenceTechnicalRoute: typeof AuthorityApplicationsReferenceTechnicalRoute
  AuthorityApplicationsReferenceIndexRoute: typeof AuthorityApplicationsReferenceIndexRoute
}

const AuthorityApplicationsReferenceRouteChildren: AuthorityApplicationsReferenceRouteChildren =
  {
    AuthorityApplicationsReferenceTechnicalRoute:
      AuthorityApplicationsReferenceTechnicalRoute,
    AuthorityApplicationsReferenceIndexRoute:
      AuthorityApplicationsReferenceIndexRoute,
  }

const AuthorityApplicationsReferenceRouteWithChildren =
  AuthorityApplicationsReferenceRoute._addFileChildren(
    AuthorityApplicationsReferenceRouteChildren,
  )

interface AuthorityRouteChildren {
  AuthorityAuditRoute: typeof AuthorityAuditRoute
  AuthorityDashboardRoute: typeof AuthorityDashboardRoute
  AuthorityNotificationsRoute: typeof AuthorityNotificationsRoute
  AuthorityRolesRoute: typeof AuthorityRolesRoute
  AuthoritySearchRoute: typeof AuthoritySearchRoute
  AuthorityApplicationsReferenceRoute: typeof AuthorityApplicationsReferenceRouteWithChildren
  AuthorityApprovalReferenceRoute: typeof AuthorityApprovalReferenceRoute
  AuthorityFinanceReferenceRoute: typeof AuthorityFinanceReferenceRoute
  AuthorityPermitsPermitNumberRoute: typeof AuthorityPermitsPermitNumberRoute
  AuthorityApplicationsIndexRoute: typeof AuthorityApplicationsIndexRoute
  AuthorityApprovalIndexRoute: typeof AuthorityApprovalIndexRoute
  AuthorityFinanceIndexRoute: typeof AuthorityFinanceIndexRoute
  AuthorityPermitsIndexRoute: typeof AuthorityPermitsIndexRoute
  AuthorityTechnicalIndexRoute: typeof AuthorityTechnicalIndexRoute
}

const AuthorityRouteChildren: AuthorityRouteChildren = {
  AuthorityAuditRoute: AuthorityAuditRoute,
  AuthorityDashboardRoute: AuthorityDashboardRoute,
  AuthorityNotificationsRoute: AuthorityNotificationsRoute,
  AuthorityRolesRoute: AuthorityRolesRoute,
  AuthoritySearchRoute: AuthoritySearchRoute,
  AuthorityApplicationsReferenceRoute:
    AuthorityApplicationsReferenceRouteWithChildren,
  AuthorityApprovalReferenceRoute: AuthorityApprovalReferenceRoute,
  AuthorityFinanceReferenceRoute: AuthorityFinanceReferenceRoute,
  AuthorityPermitsPermitNumberRoute: AuthorityPermitsPermitNumberRoute,
  AuthorityApplicationsIndexRoute: AuthorityApplicationsIndexRoute,
  AuthorityApprovalIndexRoute: AuthorityApprovalIndexRoute,
  AuthorityFinanceIndexRoute: AuthorityFinanceIndexRoute,
  AuthorityPermitsIndexRoute: AuthorityPermitsIndexRoute,
  AuthorityTechnicalIndexRoute: AuthorityTechnicalIndexRoute,
}

const AuthorityRouteWithChildren = AuthorityRoute._addFileChildren(
  AuthorityRouteChildren,
)

interface OperatorAircraftRouteChildren {
  OperatorAircraftAircraftIdRoute: typeof OperatorAircraftAircraftIdRoute
}

const OperatorAircraftRouteChildren: OperatorAircraftRouteChildren = {
  OperatorAircraftAircraftIdRoute: OperatorAircraftAircraftIdRoute,
}

const OperatorAircraftRouteWithChildren =
  OperatorAircraftRoute._addFileChildren(OperatorAircraftRouteChildren)

interface OperatorRouteChildren {
  OperatorAgentsRoute: typeof OperatorAgentsRoute
  OperatorAircraftRoute: typeof OperatorAircraftRouteWithChildren
  OperatorApplyRoute: typeof OperatorApplyRoute
  OperatorDashboardRoute: typeof OperatorDashboardRoute
  OperatorDocumentsRoute: typeof OperatorDocumentsRoute
  OperatorNotificationsRoute: typeof OperatorNotificationsRoute
  OperatorPaymentsRoute: typeof OperatorPaymentsRoute
  OperatorProfileRoute: typeof OperatorProfileRoute
  OperatorRegistrationRoute: typeof OperatorRegistrationRoute
  OperatorApplicationsReferenceRoute: typeof OperatorApplicationsReferenceRoute
  OperatorPermitsPermitNumberRoute: typeof OperatorPermitsPermitNumberRoute
  OperatorRevisionPermitNumberRoute: typeof OperatorRevisionPermitNumberRoute
  OperatorApplicationsIndexRoute: typeof OperatorApplicationsIndexRoute
  OperatorPermitsIndexRoute: typeof OperatorPermitsIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorAgentsRoute: OperatorAgentsRoute,
  OperatorAircraftRoute: OperatorAircraftRouteWithChildren,
  OperatorApplyRoute: OperatorApplyRoute,
  OperatorDashboardRoute: OperatorDashboardRoute,
  OperatorDocumentsRoute: OperatorDocumentsRoute,
  OperatorNotificationsRoute: OperatorNotificationsRoute,
  OperatorPaymentsRoute: OperatorPaymentsRoute,
  OperatorProfileRoute: OperatorProfileRoute,
  OperatorRegistrationRoute: OperatorRegistrationRoute,
  OperatorApplicationsReferenceRoute: OperatorApplicationsReferenceRoute,
  OperatorPermitsPermitNumberRoute: OperatorPermitsPermitNumberRoute,
  OperatorRevisionPermitNumberRoute: OperatorRevisionPermitNumberRoute,
  OperatorApplicationsIndexRoute: OperatorApplicationsIndexRoute,
  OperatorPermitsIndexRoute: OperatorPermitsIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorityRoute: AuthorityRouteWithChildren,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRouteWithChildren,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
